labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "duplicate"
    color: "cfd3d7"
    description: "This issue or pull request already exists"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "invalid"
    color: "e4e669"
    description: "This doesn't seem right"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"
  - name: "feature"
    color: "0e8a16"
    description: "New feature"
  - name: "fix"
    color: "d73a4a"
    description: "Bug fix"
  - name: "chore"
    color: "fef2c0"
    description: "Maintenance tasks"
  - name: "dependencies"
    color: "0366d6"
    description: "Dependency updates"
  - name: "python"
    color: "3776ab"
    description: "Python related"
  - name: "tkinter"
    color: "ff6b6b"
    description: "Tkinter related"
  - name: "dashboard"
    color: "00d4aa"
    description: "Dashboard related"
  - name: "visualization"
    color: "ff9ff3"
    description: "Data visualization"
  - name: "database"
    color: "54a0ff"
    description: "Database related"
  - name: "ui/ux"
    color: "ff9ff3"
    description: "User interface improvements"
  - name: "performance"
    color: "ff9f43"
    description: "Performance improvements"
  - name: "security"
    color: "ee5253"
    description: "Security related"
  - name: "testing"
    color: "10ac84"
    description: "Testing related"
  - name: "deployment"
    color: "5f27cd"
    description: "Deployment related"
