name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

  ## Download

  - [Source Code](https://github.com/$OWNER/$REPOSITORY/archive/v$RESOLVED_VERSION.zip)
  - [Professional Dashboard Executable](https://github.com/$OWNER/$REPOSITORY/releases/download/v$RESOLVED_VERSION/professional-dashboard.exe)

  ## Installation

  ```bash
  # Clone the repository
  git clone https://github.com/$OWNER/$REPOSITORY.git
  cd $REPOSITORY

  # Install dependencies
  pip install -r requirements.txt

  # Run the professional dashboard
  cd chapters/chapter10-complete-professional-dashboard
  python main.py
  ```

  ## Documentation

  - [Online Documentation](https://$OWNER.github.io/$REPOSITORY/)
  - [Chapter 10: Complete Professional Dashboard](https://$OWNER.github.io/$REPOSITORY/chapters/chapter10-complete-professional-dashboard/)

  ---

  *This release was automatically generated by [Release Drafter](https://github.com/release-drafter/release-drafter)*
